Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -29,9 +29,16 @@ jobs:
         run: |
           mkdir -p dist
           npx wrangler deploy src/worker.js --name bpb-worker-panel --compatibility-flag [nodejs_compat] --compatibility-date "2024-11-27" --dry-run --outdir=dist
-          npx javascript-obfuscator dist/worker.js --output workers.js
+          npx javascript-obfuscator dist/worker.js --output dist/workers.js
 
-      - name: Create Tag
+      - name: Check if workers.js exists
+        run: |
+          if [ ! -f dist/workers.js ]; then
+            echo "workers.js not found"
+            exit 1
+          fi
+
+      - name: Create Tag    
         id: create_tag
         run: |
           tagName="v$(date +%Y%m%d%H%M%S)"
@@ -55,13 +62,6 @@ jobs:
           release_name: Release ${{ steps.create_tag.outputs.TAG_NAME }}
           draft: false
           prerelease: false
-
-      - name: Check if workers.js exists
-        run: |
-          if [ ! -f dist/workers.js ]; then
-            echo "workers.js not found"
-            exit 1
-          fi
 
       - name: Upload Release Asset
         uses: actions/upload-release-asset@v1
